# Generated by Django 5.2.4 on 2025-08-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('groups', '0001_initial'),
        ('papers', '0003_alter_paperview_paper_alter_paperview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='papers.paper'),
        ),
    ]
