# Generated by Django 4.2.27 on 2026-03-01 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0005_add_research_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentDecisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_id", models.CharField(db_index=True, max_length=64)),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("agent_name", models.CharField(max_length=100)),
                ("decision_type", models.CharField(max_length=100)),
                ("reasoning", models.TextField()),
                ("confidence", models.FloatField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("latency_ms", models.FloatField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_decision_logs",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["query_id", "timestamp"],
                        name="agent_decis_query_i_d527e5_idx",
                    ),
                    models.Index(
                        fields=["session_id", "timestamp"],
                        name="agent_decis_session_6fc8ed_idx",
                    ),
                    models.Index(
                        fields=["agent_name"], name="agent_decis_agent_n_e085fb_idx"
                    ),
                ],
            },
        ),
    ]
