# Generated by Django 5.2.4 on 2025-09-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperembedding',
            name='model_version',
            field=models.CharField(default='tfidf-v1', max_length=50),
        ),
        migrations.AlterModelTable(
            name='paperembedding',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recommendationmodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userrecommendation',
            table=None,
        ),
    ]
