# Generated by Django 5.2.4 on 2025-09-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0002_alter_paperembedding_model_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecommendation',
            name='reason',
            field=models.TextField(default='Recommended by hybrid model'),
        ),
    ]
