# Generated by Django 4.2.25 on 2026-03-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0013_paper_section_summaries'),
        ('ml_engine', '0003_alter_userrecommendation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperembedding',
            name='paper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='papers.paper'),
        ),
    ]
