# Generated by Django 5.2.4 on 2025-09-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_alter_paperview_paper_alter_paperview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
