# Generated by Django 5.2.4 on 2025-10-24 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ('papers', '0004_paper_summary'),
    ]


    operations = [
    ]
