# Generated by Django 4.2.27 on 2026-02-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0006_category_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="pdf_path",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="papers/pdfs/"
            ),
        ),
    ]
