# Generated by Django 4.2.25 on 2026-02-26 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers', '0009_social_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchblogpost',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchblogpost',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchblogpost',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='researchblogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
