# Generated by Django 4.2.25 on 2026-03-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0013_paper_section_summaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='references_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
